### ISSUE TITLE
show.Images.all() results in 405 client method not allowed.

### ISSUE THREAD

**Issue by VeNoMouS** [phate89/tvdbsimple#10]
```python
>>> show = tvdb.Series('355567')
>>> art = show.Images.all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tvdbsimple/series.py", line 470, in all
    return self._get_image_type('images', language)
  File "/usr/local/lib/python2.7/dist-packages/tvdbsimple/series.py", line 480, in _get_image_type
    response = self._GET(path, params=filters)
  File "/usr/local/lib/python2.7/dist-packages/tvdbsimple/base.py", line 149, in _GET
    return self._request('GET', path, params=params, cleanJson=cleanJson)
  File "/usr/local/lib/python2.7/dist-packages/tvdbsimple/base.py", line 142, in _request
    return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
  File "/usr/local/lib/python2.7/dist-packages/tvdbsimple/base.py", line 146, in _request
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://api.thetvdb.com/series/355567/images/query
>>> 
```

**Comment by phate89** [comment]
tvdb search requires at least one between subkey, resolution or keytipe sadly but I can't force this anyway via code. I'll improve documentation
